core/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm, template_name='registration/login.html'), name="login"),
    path('logout/', views.log_out, name="logout"),
    path('register/', views.register, name="register"),
    path('edit_user/', views.edit_user, name="edit_user"),   
]

core/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('detail/', views.cart_detail, name="cart_detail"),
    path('update_quantity/',views.update_quantity, name="update_quantity"),
    path('remove_item/', views.remove_item, name="remove_item")
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace="shop")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('order/', include('orders.urls', namespace="orders"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('products/', views.product_list, name="product_list"),
    path('products/<slug:category_slug>/', views.product_list, name="product_list_by_category"),
    path('products/sort_by/<str:sort>/', views.product_list, name="product_list_sorted"),
    path('product/<int:id>/<slug:slug>', views.product_detail, name="product_detail"),
    path('profile/', views.profile, name="profile")
]

core/shop/models.py
from django.db import models
from django.urls import reverse 

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(max_length=1200)
    inventory = models.PositiveIntegerField(default=0)
    price= models.PositiveIntegerField(default=0)
    off = models.PositiveIntegerField(default=0)
    discount_price = models.PositiveIntegerField(default=0)
    weight = models.PositiveIntegerField(default=0)
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=('id', 'slug')),
            models.Index(fields=['-created']),
            models.Index(fields=['name'])
        ]
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])    

    def __str__(self):
        return self.name

class ProductFeature(models.Model):
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    product = models.ForeignKey(Product, related_name='features', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} : {self.value}"
    
class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    file = models.ImageField(upload_to='products_image/%Y%m%d')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
    
    def __str__(self):
        return self.product.name

core/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from accounts.models import ShopUser
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required

# Create your views here.

def product_list(request, category_slug=None, sort=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if sort:
        if sort == 'price_asc':  
            products = Product.objects.order_by('-discount_price').all()
        elif sort == 'price_decs':
            products = Product.objects.order_by('discount_price')
        else:
            products = products
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
    paginator = Paginator(products, 4)
    page_number = request.GET.get('page', 1)
    try:
        products = paginator.page(page_number)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        products = paginator.page(1)    
    context = {
        'products' : products,
        'category' : category,
        'categories' : categories
    }
    return render(request, 'shop/product_list.html', context)

def product_detail(request, id, slug):
    product = get_object_or_404(Product, slug=slug, id=id)
    context = {
        'product' : product 
    }
    return render(request, 'shop/product_detail.html', context)

@login_required
def profile(request):
    user = get_object_or_404(ShopUser, id=request.user.id)
    return render(request, 'shop/profile.html', {"user":user})

core/shop/templates/shop/product_detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Product{% endblock %}
{% block content %} 
<div class="header">
    <h1>Product Detail</h1>
</div>
<div class="product-container">
    <div class="product-detail">
        <h2>{{product.name}}</h2>
        <p>
            category : {{product.category}} <br>
            inventory : {{product.inventory}} <br>
            <ul>
                {% for feature in product.features.all %}
                    <li>{{feature.name}} : {{feature.value}}</li>
                {% endfor %}
                <br>
            </ul>
            <div class="price">
                <span class="orginal-price">{{product.price}}$</span> <br>
                <span class="discounted-price">{{product.discount_price}}$</span>
            </div>
            <div class="product-images">
                {% for image in product.images.all %}
                    <img src="{{image.file.url}}" width="75px" height="75px">
                {% endfor %}
            </div>
            <br>
            <button type="button" id="add-cart">Add To Cart</button>
            <div class="product-description">
                <h3>Product Description</h3>
                <p>
                    {{product.description}}
                </p>
            </div>
        </p>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function(){
        $('#add-cart').click(function(){
            var button = $(this);
            $.ajax({
                type: 'POST',
                url: '{% url "cart:add_to_cart" product.id %}',
                data: {'csrfmiddlewaretoken':'{{ csrf_token }}'},
                success: function(data){
                    $('#item_count').text(data.item_count);
                    $('#total_price').text(data.total_price);
                },
            });
        });
    });
</script>

{% endblock %}

core/shop/templates/shop/product_list.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Products{% endblock %}
{% block content %} 
<br> <br> <br> <br>
<div class="header">
    {% if category %}
    <h1>List of products by category : {{category.name}}</h1>
    {% else %}
    <h1>List of products</h1>
    {% endif %}
</div> 
<div class="container">
    <div class="small-div">
        <ul class="categories">
            <li class="category"><a href="{% url 'shop:product_list' %}">All</a></li>
            {% for category in categories %}
            <li class="category"><a href="{{category.get_absolute_url}}">{{category.name}}</a></li>
            {% endfor %}
            <br>
            <li class="sort"><a href="{% url 'shop:product_list_sorted' 'price_decs' %}">The cheapest</a></li>
            <br>
            <li class="sort"><a href="{% url 'shop:product_list_sorted' 'price_asc' %}">the most expensive</a></li>
        </ul>
    </div>
    <div class="large-div">
        {% for product in products %}
        <div class="product">
            <h2><a href="{{product.get_absolute_url}}">{{product.name}}</a></h2>
            <img class="pic" src="{{product.images.first.file.url}}">
            <div class="price">
                <span class="orginal-price">{{product.price}}$</span> <br>
                <span class="discounted-price">{{product.discount_price}}$</span>
            </div>
        </div>
        {% endfor %}
    </div>
</div>    
{% include 'partials/pagination.html' %}
{% endblock %}

core/shop/templates/shop/profile.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Products{% endblock %}
{% block content %} 
<br> <br> <br> <br>
<h1> {{user.first_name}} Profile </h1>
<p> your information : 
    {{user.username}} <br>
    {{user.phone}} <br>
    {{user.address}}
</p>
__________________________________________________ <br>
<a href="{% url 'accounts:edit_user' %}">edit user</a>
{% include 'partials/pagination.html' %}
{% endblock %}