core/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('detail/', views.cart_detail, name="cart_detail"),
    path('update_quantity/',views.update_quantity, name="update_quantity"),
    path('remove_item/', views.remove_item, name="remove_item")
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace="shop")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('order/', include('orders.urls', namespace="orders"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('verify_phone/', views.verify_phone, name="verify_phone"),
    path('verify_code/', views.verify_code, name="verify_code"),
    path('create_order/', views.create_order, name="create_order"),
    path('request/', views.send_request, name='request'),
    path('verify/', views.verify , name='verify'),
    path('orders_list/', views.orders_list, name="orders_list")
]

core/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('products/', views.product_list, name="product_list"),
    path('products/<slug:category_slug>/', views.product_list, name="product_list_by_category"),
    path('products/sort_by/<str:sort>/', views.product_list, name="product_list_sorted"),
    path('product/<int:id>/<slug:slug>', views.product_detail, name="product_detail"),
    path('profile/', views.profile, name="profile")
]

core/cart/models.py
from django.db import models

# Create your models here.

core/cart/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from django.http import JsonResponse

# Create your views here.

@require_POST
def add_to_cart(request, product_id):
    try:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.add(product)
        context = {
            'item_count': len(cart),
            'total_price': cart.get_total_price()
        }
        return JsonResponse(context)
    except:
        return JsonResponse({'error': "InvalidRequest"})
    
def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_detail.html', {'cart':cart})

@require_POST
def update_quantity(request):
    item_id = request.POST.get('item_id')
    action = request.POST.get('action')
    try:
        product = get_object_or_404(Product, id=item_id)
        cart = Cart(request)
        if action == 'add':
            cart.add(product)
        elif action == 'decrase':
            cart.decrase(product)
        context = {
            'item_count': len(cart),
            'total_price': cart.get_total_price(),
            'success': True, 
            'quantity': cart.cart[item_id]['quantity'],
            'price': cart.cart[item_id]['price'],
            'total': cart.cart[item_id]['quantity'] * cart.cart[item_id]['price'],
            'final_price': cart.get_final_price(),
        }  
        return JsonResponse(context)  
    except:
        return JsonResponse({'success':False, 'error':"ItemNotFound"})


@require_POST
def remove_item(request):
    item_id = request.POST.get('item_id')
    try:
        product = get_object_or_404(Product, id=item_id)
        cart = Cart(request)
        cart.remove(product)

        context = {
            'item_count': len(cart),
            'total_price': cart.get_total_price(),
            'final_price': cart.get_final_price(),
            'success': True,
        }  
        return JsonResponse(context)
    except:
        return JsonResponse({'success': False, 'error': 'Item not found!'})

core/cart/templates/cart/cart_detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Cart{% endblock %}
{% block content %} 
<br> <br> <br> <br>
    <div class="header">
        <h1>Shopping Cart</h1>
    </div>
    <div class="cart-detail-container">
        {% for item in cart %}
            <div class="product-item" data-item-id="{{item.product.id}}">
                <a href="{% url 'shop:product_detail' item.product.id item.product.slug %}">
                    <img src="{{ item.product.images.first.file.url }}" class="product-image">
                </a>
                <div class="product-info">
                    <h3>
                        <a href="{% url 'shop:product_detail' item.product.id item.product.slug %}">
                            Product Name : {{item.product.name}}
                        </a>
                    </h3>
                    <p>Quantity : <span id="item-quantity-{{item.product.id}}">{{item.quantity}}</span></p>
                    <p>Unit price : <span id="">{{item.price}}</span></p>
                    <p>Total price : <span id="item-total-{{item.product.id}}">{{item.total}}</span></p>
                </div>
                <div class="actions">
                    <div class="quantity-add">+</div>
                    <div class="quantity-decrase">-</div>
                    <div class="quantity-remove">remove</div>
                </div>
            </div>
        {% endfor %}    
    </div>
    <div class="total_price">
        <p> Total Price <span id="item-total-price">{{ cart.get_total_price }}</span> $ </p>
        <p> Shipping cost <span id="item-post-price">{{ cart.get_post_price }}</span> $ </p>
        <p> Final cost <span id="item-final-price">{{ cart.get_final_price }}</span> $ </p>
    </div>
    <div class="checkout-buttons">
        <div class="continue-btn"><a href="{% url 'orders:verify_phone' %}">Continue shopping</a></div>
        <div class="back-btn"><a href="{% url 'shop:product_list' %}">Back to the product list</a></div>
    </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function(){
        $('.quantity-add').on('click', function(){
            updateQuantity($(this).closest('.product-item').data('item-id'), 'add');
        });

        $('.quantity-decrase').on('click', function(){
            updateQuantity($(this).closest('.product-item').data('item-id'), 'decrase');
        });

        $('.quantity-remove').on('click', function(){
            removeItem($(this).closest('.product-item').data('item-id'));
        });

        function updateQuantity(itemId, action){
            $.ajax({
                type:'POST',
                url:'{% url "cart:update_quantity" %}',
                data:{
                    'item_id':itemId,
                    'action':action,
                    'csrfmiddlewaretoken':'{{ csrf_token }}'
                },
                success: function(response){
                    if (response.success){
                        $('#item_count').text(response.item_count);
                        $('#total_price').text(response.total_price);
                        $('#item-quantity-'+itemId).text(response.quantity);
                        $('#item-total-'+itemId).text(response.total);
                        $('#item-total-price').text(response.total_price);
                        $('#item-final-price').text(response.final_price);
                    }else{
                        alert('Error updating quantity!');
                    }
                }
            });
        }

        function removeItem(itemId){
            $.ajax({
                type: 'POST',
                url: '{% url "cart:remove_item" %}',
                data: {
                    'item_id': itemId,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(data){
                    if (data.success) {
                        $('#item_count').text(data.item_count);
                        $('#total_price').text(data.total_price);
                        $('#item-total_price').text(data.total_price);
                        $('#item-final_price').text(data.final_price);
                        $(`.product-item[data-item-id=${itemId}]`).remove();
                    } else {
                        alert('Error remove quantity!');
                    }
                }

            });
        }

    });
</script>
{% endblock %}